language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.6.6
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
  - mysql
  - postgresql
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.2_ndl.gemfile
  - gemfiles/rails_5.2_loc.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: UIe53zKTV3GYyi07+PIkndBzOYYU2bWDNuGUNbbTvx0tZ77SEoY32cYPn7NrdydIRT+WPEglDsYHXH2Vp8onO/xUQkt127zP2vGn5jEfL+GpAe75EhR4QkyrIZXItoSfIjXifEkkniSEUUT9PKk4dkTJv1kIancufImYj/EQX1A=
sudo: false
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - chromium-browser
jdk:
  - openjdk8
dist: xenial
