language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_ndl.gemfile
  - gemfiles/rails_4.2_loc.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: UIe53zKTV3GYyi07+PIkndBzOYYU2bWDNuGUNbbTvx0tZ77SEoY32cYPn7NrdydIRT+WPEglDsYHXH2Vp8onO/xUQkt127zP2vGn5jEfL+GpAe75EhR4QkyrIZXItoSfIjXifEkkniSEUUT9PKk4dkTJv1kIancufImYj/EQX1A=
sudo: false
